/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;
import org.example.phone.OS;
import org.example.phone.GetInstance;


public class App {
 

    public static void main(String[] args) {
        // OS obj = new Android();
        // obj.specs();

        // OS obj1 = new IOS();
        // obj1.specs();

        // OS obj2 = new Windows();
        // obj2.specs();

        // ! Since the above methods are visible by users

        // todo : Below is the implementation of Factory design pattern
        GetInstance getInstance = new GetInstance();
        OS obj = getInstance.getInstance("Android");
        obj.specs();

    }
}
