/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.core.exc.StreamReadException;
import com.fasterxml.jackson.databind.DatabindException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    // todo : Read Json files
    public void readJson(File file) throws StreamReadException, DatabindException, IOException
    {
        var objectMapper = new ObjectMapper();
        Trade[] trades = objectMapper.readValue(file, Trade[].class);

        for(Trade trade : trades){
            System.out.println(trade);
        }
    }

    // todo :  read and write Json
    public void writeOutput(File file, File outputFile) throws StreamReadException, DatabindException, IOException
    {
        var objectMapper  =  new ObjectMapper();
        Trade[] trade = objectMapper.readValue(file, Trade[].class);

        objectMapper.writeValue(outputFile, trade);
    }

    // todo :read json files with fancy names
    public void read_fancy(File file) throws StreamReadException, DatabindException, IOException
    {
        var objectMapper = new ObjectMapper();
        TradeFanvy[] trade = objectMapper.readValue(file, TradeFanvy[].class);

        for(TradeFanvy  fanvy: trade){
            System.out.println(fanvy);
        }
    }

    public static void main(String[] args) throws StreamReadException, DatabindException, IOException {
        
        File trades = new File("src/main/java/org/example/trade.json"); 
        App main = new App();
        System.out.println("Reading input Files");
        main.readJson(trades); 
        
        System.out.println("Writing output Files");
        File  output = new File("src/main/java/org/example/tradeOutput.json");
        main.writeOutput(trades,output);

        main.readJson(output);

        System.out.println("Reading with Fancy Names");
        File fancyNames=new File ("src/main/java/org/example/tradeFancy.json");
        main.read_fancy(fancyNames);
    }
}
